### ISSUE TITLE
Ошибка при запросе данных с разбивкой по action_breakdowns

### ISSUE THREAD

**Issue by zkostitsyn** [selesnow/rfacebookstat#1]
Функция:
`AdStat <- fbGetMarketingStat(accounts_id = "act_xxx",
                             level = "ad",
                             action_breakdowns = "action_type",
                             fields = "date_start,campaign_name,adset_name,total_actions,spend,actions",
                             date_start = "2018-03-10",
                             date_stop = Sys.Date()-1,
                             api_version = "v2.12",
                             request_speed = "slow",
                             access_token = "xxx")`

Ошибка:
in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 1, 0
In addition: Warning message:
In data.frame(..., check.names = FALSE) :
  row names were found from a short variable and have been discarded

**Comment by selesnow** [comment]
Ошибку исправил и вообще привёл к нормальному виду работу с action breakdowns, теперь каждый actions будет в отдельном поле, и не будет дублить остальные данные.

**Comment by zkostitsyn** [comment]
Спасибо!
