### ISSUE TITLE
Долгая загрузка

### ISSUE THREAD

**Issue by Wreitlein** [selesnow/rfacebookstat#10]
Здравствуйте. Столкнулся с такой проблемой, что загрузка одного запроса весом в пару килобайт может занимать до 20 минут. 
Проблема встречается и при обновлении в power bi и при запуске кода напрямую в R.
Причём через час всё может подгружаться моментально, т.е. эта ошибка возникает периодически.
Пример кода:
`library(rfacebookstat)
fb_id <- fbGetMarketingStat(accounts_id = "act_111111111",
                                                     level = "ad",
                                                     fields = "ad_id,ad_name",
                                                     date_start = "2018-07-01",
                                                     date_stop = Sys.Date(),
                                                     access_token = "1111111111111")`

**Comment by selesnow** [comment]
Добрый день, это наверняка связано с тем что у вашего приложения низкий уровень доступа к API Facebook, скорее всего уровень Development. 

Отвечает за скорость загрузки аргумент request_speed, подробнее о работе с этим аргумент можно почитать [тут](https://alexeyseleznev.wordpress.com/2017/12/26/rfacebookstat-1-5-0-%D0%BA%D0%B0%D0%BA-%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%B0%D1%80%D0%B3%D1%83%D0%BC/).

**Comment by Wreitlein** [comment]
Понял, спасибо.
