### ISSUE TITLE
Application does not have the capability to make this API call

### ISSUE THREAD

**Issue by MarovMarov** [selesnow/rfacebookstat#11]
Пытаюсь получить рекламную статистику из Facbook.
Установил Rsudio, пакет rfacebookstat, зарегистрировал приложение. Все делал по инструкции [Neatpeak](https://netpeak.net/ru/blog/kak-zagruzit-statistiku-reklamnykh-kampanii-iz-api-facebook-s-pomoshch-yu-yazyka-r/)
В итоге получаю ошибку:

**Запрос**
 `token <- "Здесь_был_токен"
 fb_data <- fbGetMarketingStat(accounts_id = "act_7777777777777",
                               level = "campaign",
                               fields = "campaign_name,actions",
                               action_breakdowns = "action_link_click_destination",
                               date_start = "2019-01-20",
                               date_stop = "2019-01-20",
                               interval = "month",
                               api_version = "v3.2",
                              access_token = token)`

**Ошибка**
Error in fbGetMarketingStat(accounts_id = "act_7777777777777", level = "campaign",  : 
  (#3) Application does not have the capability to make this API call.

**Comment by selesnow** [comment]
У вас проблема где то в настройках созданного приложения, попробуйте там всё проверить.
