### ISSUE TITLE
fbGetMarketingStat выдает ошибку

### ISSUE THREAD

**Issue by stavrovskaya** [selesnow/rfacebookstat#17]
Добрый день, Алексей,

использую функцию fbGetMarketingStat. использование как в документации выдает ошибку, что применяется запрещенная версия api . 
> fb <- fbGetMarketingStat(accounts_id = "act_XXX",
+                          level = "account",
+                          fields = "campaign_name,adset_name,ad_name,impressions,clicks,spend",
+                          date_start = start_date,
+                          date_stop = end_date,
+                          interval = "day",
+                          access_token = longToken)
Error in fbGetMarketingStat(accounts_id = "act_XXX", level = "account",  : 
  (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v3.3.
Задаю параметр api_version, выдает ошибку:
> fb <- fbGetMarketingStat(accounts_id = "act_XXX",
+                          api_version = "v3.3",
+                          level = "account",
+                          fields = "campaign_name,adset_name,ad_name,impressions,clicks,spend",
+                          date_start = start_date,
+                          date_stop = end_date,
+                          interval = "day",
+                          access_token = longToken)
Error: Argument 'txt' must be a JSON string, URL or file.

**Comment by selesnow** [comment]
спасибо за информацию, завтра проверю и думаю начну перевод пакета на новую версию.

**Comment by selesnow** [comment]
я понял в чем ошибка, в ближайшем релизе её исправлю, пока можете установить версию пакета с CRAN с помощью `install.packages('rfacebookstat')`.
И при использовании `api_version('v3.3')` пакет по идее должен корректно работать.

**Comment by stavrovskaya** [comment]
Да, заработало, спасибо большое!

**Comment by selesnow** [comment]
Добрый день ещё раз.

В целом работы по переезду пакета на работу с Facebook API Marketing v3.3 практически завершены, и я приступаю к его тестированию.

Для загрузки тестовой версии используйте код: `devtools::install_github("selesnow/testspace", subdir = "rfacebookstat", upgrade = "never")`

Буду благодарен если протестируете его и напишите мне в случае обнаружения ошибки.

**Comment by stavrovskaya** [comment]
Добрый день, с указанием версии 3.3 все работает, без нет.

**Comment by selesnow** [comment]
Судя по всему вы просто установили пакет из CRAN, а там только сегодня появилась новая версия.
Но уже можно обновить пакет в том числе и из CRAN, подробно обо всех доработках можно узнать [тут](https://github.com/selesnow/rfacebookstat/releases/tag/1.9.0).
