### ISSUE TITLE
Ошибки функции fbGetAdAccounts

### ISSUE THREAD

**Issue by stavrovskaya** [selesnow/rfacebookstat#18]
Добрый день,

Для бизнес менаджеров, у которых много рекламных аккаунтов (9-10), получаю ошибку: http://joxi.ru/8AnkP8oIznZ7lr
Если запускать много раз, иногда срабатывает

Для бизнес менаджеров, у которых всего один рекламный аккаунт, получаю ошибку:
http://joxi.ru/Y2L9ZxYS7dkLzA

**Comment by selesnow** [comment]
По первой ошибке скорее всего проблема с вашим уровнем доступа к апи чем с пакетом.

По поводу второй ошибки, где в бизнес менеджере всего 1 аккаунт мне сложно пока что то сказать т.к. не могу протестировать в таком режиме функцию, т.к. у меня нет бизнесс менеджера с одним аккаунтом.

Возможно это какой то ваш тестовый бизнес менеджер и вы на время могли бы мне предоставить к нему доступ, для тесиирования и отладки?

**Comment by stavrovskaya** [comment]
1. Если проблемы с уровнем доступа, тогда странно, что иногода срабатывает. Скорее проблема с самим апи, timeout запроса к серверу может быть.
2. Про доступ к тестовому бизнес менеджеру спрошу наших таргетологов и напишу Вам

**Comment by stavrovskaya** [comment]
Написала Вам на почту, можно сделать доступ.

**Comment by selesnow** [comment]
Пока ждём с вашей стороны ответа, возмлжно там проблема с доступом

**Comment by selesnow** [comment]
@stavrovskaya 
Попробуйте переустановить пакет, с версии 2.0.0 большинство функций были значительно доработаны, синтаксис пакета стал лаконичнее, а работа стабильнее.

Подробности релиза можно узнать по [ссылке](https://github.com/selesnow/rfacebookstat/releases/tag/2.0.0)
