### ISSUE TITLE
Аргумент нулевой длины

### ISSUE THREAD

**Issue by Amakiavelli** [selesnow/rfacebookstat#23]
При авторизации выдаёт вот такую ошибку http://prntscr.com/qoiqoz  Как можно исправить?

**Comment by Sensirex** [comment]
> При авторизации выдаёт вот такую ошибку http://prntscr.com/qoiqoz Как можно исправить?

тоже с этим стонулся, всё из за невнимательности. Нужно настроить приложение по инструкции и установить все параметры (options) и только потом авторизоваться

**Comment by selesnow** [comment]
@Amakiavelli подскажите получилось разобраться с проблемой?

Явно у вас что то с настройками приложения, скорее всего вы вывели его из статуса "В разработке".

Посмотрите этот [плейлист](https://www.youtube.com/watch?v=NgfWELbM6Fk&list=PLD2LDq8edf4qed2KVKfXmKdh0OQcdj9gw) и попробуйте сделать в точности как там показано.
