### ISSUE TITLE
Добавление параметра Filtering в fbGetAdCreative и еще одного поля adlabels

### ISSUE THREAD

**Issue by aesstus** [selesnow/rfacebookstat#25]
Просьба добавить параметр filtering в fbGetAdCreative для случаев, когда очень много объявлений в аккаунте.
Плюс просьба добавить поле adlabels. Это единственное нормальное поле, за которое можно зацепиться при фильтрации, так как согласно https://developers.facebook.com/docs/marketing-api/reference/ad-creative/ самого логичного поля для этого случая campaign_id или campaign_name у фб по апи нет.

**Comment by selesnow** [comment]
Это уже реализовано.
