### ISSUE TITLE
Please reduce the amount of data you're asking for, then retry your request

### ISSUE THREAD

**Issue by ErezLo** [selesnow/rfacebookstat#26]
Hi

I am trying to get my facebook creatives images using this code

ads_creative <- fbGetAdCreative(accounts_id = "act_11111",
                                api_version = 'v8.0',
                                access_token = token)

which results this error:
Please reduce the amount of data you're asking for, then retry your request

How do I reduce the data request?
Thanks

**Comment by selesnow** [comment]
Hi, Try to request data for a shorter period.

I will fix it on this week.
