### ISSUE TITLE
attribution_window issue

### ISSUE THREAD

**Issue by dmacoritto** [selesnow/rfacebookstat#28]
Hello everyone,

I am writing on this forum as I have encountered an issue when wishing to change the attribution window in the function fbGetMarketingStat(). In the help file, it is documented that the attribution window can contain conversions post-view and post-clicks such as for instance "7d_view_1d_click". Nonetheless, as soon as I try to assign this to the attribution window variable, an error message is returned : 

"Error in fbGetMarketingStatHelper(accounts_id = accounts_id, sorting = sorting,  : 
  (#100) action_attribution_windows[0] must be one of the following values: 1d_view, 7d_view, 28d_view, 1d_click, 7d_click, 28d_click, dda, default"

From the error message, it seems that the "7d_view_1d_click" is not supported. Any help on that topic would be greatly appreciated.

Best regards

Darko

**Comment by selesnow** [comment]
Hello, now API Facebook does not support composite attribution models, you need to request 7d_view and 1d_click in turn and then recumulate the result.

![](http://img.netpeak.ua/alsey/1BG0RJH.png)

https://developers.facebook.com/docs/marketing-api/ad-rules/guides/roas-ad-rules/
