### ISSUE TITLE
Invalid Scopes: manage_pages, user_friends

### ISSUE THREAD

**Issue by maraevdima** [selesnow/rfacebookstat#29]
В ФБ добавился "Тип приложения", при запросе токена выдается сообщение о нехватке прав для выбранного типа.
Если выбрать тип приложения "Бизнес", то при получении токена возникает ошибка.

Ошибка:
Invalid Scopes: manage_pages, user_friends. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

Подскажите, пожалуйста, как это полечить?

**Comment by selesnow** [comment]
Добрый день, попробуйте пройти авторизацию через вшитое в пакет приложение, скорее всего для Бизнеса Facebook вам не даст через своё приложение авторизоваться т.к. вам надо пройти проверку, я например проверку проходил года два, это правда очень сложно сделать. 

И второе я ещё не перевёл пакет на версию API 10.0, т.е. тоже пока лучше вшитое приложение использовать.

**Comment by maraevdima** [comment]
Алексей, спасибо большое! А что такое "вшитое в пакет приложение"? Можно пожалуйста ссылочку где почитать?

**Comment by selesnow** [comment]
Конечно, самое первое видео в плейлисте rfacebookstat как раз о том, как пройти через вшитое приложение авторизацию. 

https://www.youtube.com/watch?v=SgcxDqZ-5Qg&list=PLD2LDq8edf4pItOb-vZTG5AXZK2niJ8_R&index=1&t=1s

**Comment by maraevdima** [comment]
Добрый вечер, Алексей! Все работает, спасибо) Я только теперь не пойму зачем вообще со своим приложением заморачиваться, если через вшитое все работает)

**Comment by selesnow** [comment]
Дело в том что facebook непредсказуем, он и моё приложение может забанить в любой момент, и регулярно выкатывает какие то непонятные обновления в API.
