### ISSUE TITLE
Collecting Purchase with shared item data

### ISSUE THREAD

**Issue by kandujiwandono** [selesnow/rfacebookstat#31]
hi there,
can i get purchases with shared item data from my facebook ads account using this packages?

thanks

**Comment by selesnow** [comment]
Hello, yes.

You need to request `"actions"` in `fields` and  `"action_type"` in `action_breakdowns `.

Example:

```
data <- fbGetMarketingStat(
          level  = "adset",
          fields = "campaign_name,
                    adset_name,
                    impressions,
                    clicks,
                    reach,
                    spend,
                    actions,
                    action_values",
          date_preset = 'last_7d', 
          action_breakdowns = "action_type"
          ) 
```

**Comment by kandujiwandono** [comment]
![image](https://user-images.githubusercontent.com/57737288/127129495-ea482708-9bd2-4232-91c0-0488ea16e34b.png)

pic above showed the result from R. there are no data captured.

but this pic below is from facebook ads manager.
![image](https://user-images.githubusercontent.com/57737288/127129581-b74d0b67-a89d-4d14-bc7c-4d15a12f1bcb.png)
there are 10mil purchased conversions value.

can you tell me why this is happened?

**Comment by selesnow** [comment]
A lot of different actions come to the "actions" field, you need to check all the fields whose names contain purchase.

**Comment by kandujiwandono** [comment]
i already look all the fields and its not there. 
is it possible i did something wrong with my pixel tracking?

**Comment by selesnow** [comment]
Unfortunately, I do not set up advertising campaigns on Facebook, so I find it difficult to answer this question, but if you see the data in the web interface, then your pixel works correctly.

**Comment by kandujiwandono** [comment]
ah i see,
thank you for your answer.

cheers

**Comment by kandujiwandono** [comment]
i have this script
 `data_tes_mp <- fbGetMarketingStat(level = "campaign",
                               fields = "campaign_id,converted_product_quantity,converted_product_value",
                               date_start = "2021-07-16",
                               date_stop = "2021-07-16")`

 and here's the output
![image](https://user-images.githubusercontent.com/57737288/127444019-084a0ccc-a3d3-4b4e-a96d-2c8de09ad1d3.png)

can you tell me what is converted product quantity and value means?

and can i get result like pic below, using your packages? 
let say i want to get "purchased shared item" or "add to card conversion value for shared item" column only. not both of them
thanks
![image](https://user-images.githubusercontent.com/57737288/127444676-3efcaaeb-24ce-45f3-9001-c7c8e115ec7e.png)

**Comment by selesnow** [comment]
_can you tell me what is converted product quantity and value means?_

![](http://img.netpeak.ua/alsey/1RJ4JN4.png)
https://developers.facebook.com/docs/marketing-api/insights/parameters/v11.0

---

_and can i get result like pic below, using your packages?_
You must convert converted_product_value column:

```r
data_tes_mp$converted_product_value <- as.integer(data_tes_mp$converted_product_value) / 1000
```

---

_let say i want to get "purchased shared item" or "add to card conversion value for shared item" column only. not both of them
thanks_

Try to specify only the fields you need in the `fields` argument.
