### ISSUE TITLE
Facebook Ads API Version v12.0

### ISSUE THREAD

**Issue by olafodinn1** [selesnow/rfacebookstat#33]
Hi Selesnow

I'm currently receiving an error #2635 when trying to run the funciton fbGetAddAccounts (). I states the following: "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v12.0"

Are you currently working on the ads API  , if so when do you think you'll be able to update the API calls to Version 12.0?

Kind Regards

Olaf

**Comment by selesnow** [comment]
I am planning to upgrade to version 12 soon.

For now, you can just use the `options(rfacebookstat.api_version  = "v12.0")`.

**Comment by selesnow** [comment]
Done!
