### ISSUE TITLE
Error in `vec_assign()`

### ISSUE THREAD

**Issue by angelnikolov56** [selesnow/rfacebookstat#37]
Hi Alexey! Great package! 

I'm experiencing some issues with fbGetMarketingStat() since I updated R to version 4.2.0 and tidyverse to 1.3.1. The issue occurs when I include "actions" in the fields argument. I'm getting the following error:

Error in `vec_assign()`:
! Can't convert `replace$val` <double> to match type of `data$val` <character>.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/vctrs_error_incompatible_type>
Error in `vec_assign()`:
! Can't convert `replace$val` <double> to match type of `data$val` <character>.
---
Backtrace:
  1. rfacebookstat::fbGetMarketingStat(...)
 13. tidyr:::replace_na.data.frame(., list(val = 0))
 14. vctrs::vec_assign(...)
Run `rlang::last_trace()` to see the full context.
---
Backtrace:
     ▆
  1. ├─rfacebookstat::fbGetMarketingStat(...)
  2. │ └─rfacebookstat:::fbGetMarketingStatHelper(...)
  3. │   ├─rfacebookstat:::fbAction(answerobject)
  4. │   └─rfacebookstat:::fbAction.default(answerobject)
  5. │     └─purrr::map_df(...)
  6. │       └─purrr::map(.x, .f, ...)
  7. │         └─rfacebookstat .f(.x[[i]], ...)
  8. │           └─... %>% bind_cols(other_col, .)
  9. ├─dplyr::bind_cols(other_col, .)
 10. │ └─rlang::list2(...)
 11. ├─tidyr::pivot_wider(...)
 12. ├─tidyr::replace_na(., list(val = 0))
 13. └─tidyr:::replace_na.data.frame(., list(val = 0))
 14.   └─vctrs::vec_assign(...)
 15.     └─vctrs `<fn>`()
 16.       └─vctrs::vec_default_cast(...)
 17.         └─vctrs::stop_incompatible_cast(...)
 18.           └─vctrs::stop_incompatible_type(...)
 19.             └─vctrs:::stop_incompatible(...)
 20.               └─vctrs:::stop_vctrs(...)
 21.                 └─rlang::abort(message, class = c(class, "vctrs_error"), ..., call = vctrs_error_call(call))

Kind regards
Angel

**Comment by selesnow** [comment]
Hi, install dev version `devtools::install_github('selesnow/rfacebookstat')`.

This it solved
