### ISSUE TITLE
Переведите пожалуйста функцию с curl на httr

### ISSUE THREAD

**Issue by oleksii-yeskov** [selesnow/rfacebookstat#5]
Периодически скрипт даёт ошибку 
Error in curl::curl_fetch_memory(url, handle = handle): Empty reply from server 
Request failed [ERROR]. Retrying in 1 seconds...

**Comment by selesnow** [comment]
Переписал функцию fbGetMarketingStats с пакета RCurl на httr, переустанови пакет и по идее всё будет работать значительно стабильнее.
