### ISSUE TITLE
Поле fields без пробелов и переноса строки

### ISSUE THREAD

**Issue by oleksii-yeskov** [selesnow/rfacebookstat#6]
В скрипте вызывает ошибку поле fields  если перечислить поля с пробелами. 
Приходится использовать костыль gsub(" ", "", "ad_id, ad_name, adset_id, adset_name, campaign_id, campaign_name, impressions, inline_link_clicks, spend, action_values", fixed = TRUE)
Если получится обойтись без этого - будет аккуратнее. Спасибо

**Comment by selesnow** [comment]
Спасибо, беру в работу, в ближайшее время будет реализовано

**Comment by selesnow** [comment]
Готово, данная доработка внесена в версию на GitHub, на CRAN она появится позже, с другими обновлениями.
