### ISSUE TITLE
Что-то не так с токеном

### ISSUE THREAD

**Issue by tytanya** [selesnow/rfacebookstat#7]
Запускаю запрос на получение токена
token <- fbGetToken(app_id = 257****9327)
Получаю ошибку-предупреждение: Invalid Scopes: business_management, manage_pages. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

Нажимаю окей, получаю токен: http://take.ms/uYoWv
После чего пытаюсь получить долговременный токен 
longtime_token <- fbGetLongTimeToken(
+     client_id = здесь пишу ид приложения,
+     client_secret = "пишу секрет приложения",
+     fb_exchange_token = token)

Выдает ошибку 
{
   "error": {
      "message": "Invalid OAuth access token.",
      "type": "OAuthException",
      "code": 190,
      "fbtrace_id": "FK5eNNQUjr7"
   }
}

Изначально временный токен совсем не выдавал, добавила в домен приложения github.io, после этого хотя бы временный токен стал отдавать

**Comment by selesnow** [comment]
Добрый день, подскажите вы установили действительные URI перенаправления для OAuth?

![](http://img.netpeak.ua/alsey/152577078590_kiss_45kb.png)

Доверительный URI должен быть https://selesnow.github.io/rfacebookstat/getToken/get_token.html

Вроде в самом коде у вас ошибок нет, скорее это в настройках приложения.

**Comment by tytanya** [comment]
Добрый,
Да:
http://take.ms/4Frdc

**Comment by selesnow** [comment]
Смотрите, у нас всё же немного разные настройки на "Вход через Facebook", попробуйте заменить те что я выделил на скрине, у вас они включены.
+ Требовать HTTPS
+ Использовать строгий режим для URI перенаправления

![](http://img.netpeak.ua/alsey/152594283888_kiss_44kb.png)

**Comment by selesnow** [comment]
Немного переписал функцию `fbGetLongTimeToken`, попробуйте переустановить пакет и ещё раз поменять краткосрочный токен на долгосрочный.

Для обновления пакета запустить команду `devtools::install_github("selesnow/rfacebookstat")`

**Comment by tytanya** [comment]
Не могу поменять эти две настройки: переключатель не переставляется в "Нет".

При запросе токена одноразового получаю:
Ваш Токен доступа:
100
Может это заголовок запроса со статусом, а не токен?

**Comment by selesnow** [comment]
Это скорее всего код ошибки, может попробуете создать с нуля новое приложение?

Давайте поступим таким образом:

1. Вы создаёте новое приложение и пробуете получить обычный токен и поменять его на долгосрочный.

2. Если по прежнему у вас возникает ошибка, по возможности скиньте мне уже в личку можно например в телеграмме код с вашим id и секретом приложения, а я попробую у себя получить токен, если получится воспроизвести вашу ошибку я думаю я смогу с ней разобраться.

Пока я думаю что ошибка где то в настройках приложения.

**Comment by selesnow** [comment]
Вот что я в справке по ошибке 100 нашел, скорее всего вы не верный ID приложения указываете.

![](http://img.netpeak.ua/alsey/152596499274_kiss_15kb.png)

Дело в том, что токен в FB не может быть таким коротким как на вашем первом скрине

![](http://img.netpeak.ua/alsey/152596513204_kiss_47kb.png)

Токен состои примерно из 165 символов, но никак не из трёх.

По идее в самом URL на который вас перенаправляет пакет должно быть сообщение об ошибке, посмотрите GET параметры наверняка в них будет подсказка.

**Comment by tytanya** [comment]
Создала новое приложение
http://take.ms/E1xc7
http://take.ms/CpvIjb
Опубликовала

Выдает ошибку: http://take.ms/jHvRU
Добавляю github.io в домены приложений
запускаю token <- fbGetToken(app_id = 1506478259475544)
После этого все равно вместо токена вылетает цифра 100

**Comment by selesnow** [comment]
У вас ошибка в основных настройках, в доменах приложения:

Переходим в настройки:
![](http://picsee.net/upload/2018-05-12/58cfacd3d869.png)

Должно быть selesnow.github.io:

![Настройки / Домены приложения](http://picsee.net/upload/2018-05-12/07962aa6d3fb.png)

У вас в настройках
![](http://picsee.net/upload/2018-05-12/a07800922d4b.png)

**Comment by tytanya** [comment]
Спасибо!
В этой статье https://netpeak.net/ru/blog/kak-zagruzit-statistiku-reklamnykh-kampanii-iz-api-facebook-s-pomoshch-yu-yazyka-r/
у вас другой домен приложения, может стоит поправить?
И здесь тоже другой https://selesnow.github.io/rfacebookstat/

**Comment by tytanya** [comment]
Теперь вот такая ошибка:
Invalid Scopes: business_management, manage_pages. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions
и снова вместо токена ошибка 100

**Comment by selesnow** [comment]
По поводу ошибки в статье и документации, спасибо, поправлю, просто нехватает времени всегда держать их в актуальном состоянии.

По новой ошибке, возможно Facebook что то поменял, смотрите у меня в продукты добавлен API Marketing, а у вас только вход через Facebook, возможно причина в этом, т.е. вам надо 

![](http://s2.micp.ru/o381n.png)

Как его включить:
1. Нажать + возле продуктов.

2. Найти API Marketing и нажать настроить.
![](http://s2.micp.ru/x616q.png)

По идее это должно помочь.

**Comment by tytanya** [comment]
Не помогло, та же ошибка. Но у меня зеленым и не подсвечивается галочка у API Marketing.
Пишет, что 
Только администраторы могут привязывать приложения к компаниям
Обратитесь к администраторам  компании «Рекламное агентство ....», чтобы привязать свое приложение к этой компании.
А я и так администратор данного Бизнес аккаунта

**Comment by selesnow** [comment]
Подскаже вам так и не удалось разобраться с токеном?

**Comment by tytanya** [comment]
Добрый день, так и не получилось выгрузить данные.

**Comment by selesnow** [comment]
> А я и так администратор данного Бизнес аккаунта

Смотрите, помимо того, что вы администратор Бизнес менеджера, вам отдельно ещё и к каждому рекламному аккаунту необходимо иметь доступ, в FB такая немного неудобная система доступов, возможно в этом проблема?

**Comment by Lushenius** [comment]
Алексей, добрый день!

Аналогичная проблема с получением токена. Все ссылки поправил после прочтения этой ветки, я являюсь администратором приложения, бизнес менеджера и рекламных аккаунтов. 
При попытке получения первого токена появляется следующая ошибка - http://prntscr.com/kfrod1 

Вы пишите про API marketing в приложении. У меня по этой вкладке висит статус не завершен (и галочка серый цветом подсвечена) - http://prntscr.com/klmbsn
При попытке закончить настройку просит установить SDK - http://prntscr.com/klmc9y

**Comment by selesnow** [comment]
добрый день, попробуйте установить  SDK, последнее время facebook  ввёл много изменений в доступе к api marketing, я сам пока разбираюсь.

**Comment by MarovMarov** [comment]
Проблема с получением токена актуальна.
Удалось ли как-то ее решить?
![image](https://user-images.githubusercontent.com/46968476/51660030-7a247380-1fbd-11e9-8777-3d87ea27756d.png)
Данный аллерт выходит при попытке сделать запрос:
token <- fbGetToken(app_id = xxxxxxxxxxxxxxxxxxxxxxxxx)

**Comment by Lushenius** [comment]
К сожалению, не удалось.

Чт, 24 січ. 2019, 08:51 MarovMarov користувач notifications@github.com пише:

**Comment by selesnow** [comment]
Появилось новое предположение, возможно вы вывели своё приложение из статуса "В разработке"?

![](http://img.netpeak.ua/alsey/155376425960_kiss_10kb.png)
