### ISSUE TITLE
Требование переключиться на версию api 3.1

### ISSUE THREAD

**Issue by rledovskiy** [selesnow/rfacebookstat#8]
Алексей, добрый день!

Спасибо за отличный пакет!

Видимо, с совсем недавнего времени он перестал работать, так как fb переключился на версию api 3.1. В результате этого функция fbGetMarketingStat возвращает ошибку:
(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v3.1.

Указание в качестве одного из аргументов api_version  = 'v3.1', к сожалению, не помогает :-(

**Comment by selesnow** [comment]
Сегодня я перевёл большую часть функций на версию v3.1, попробуйте переустановить пакет и заново запустить нужные функции.

Переустановка пакета:
```r
devtools::install_github('selesnow/rfacebookstat')
```

**Comment by rledovskiy** [comment]
Алексей, спасибо за оперативный ответ!

Заработало!
