### ISSUE TITLE
Работа пакета с полями типа list<AdsActionStats>

### ISSUE THREAD

**Issue by rledovskiy** [selesnow/rfacebookstat#9]
Алексей, добрый день!

Пакет работает очень круто!

Но у меня никак не получается получить данные по количеству установок приложения...
Насколько я понимаю, за эту метрику отвечает поле Actions, однако его тип не numeric string, а list(AdsActionStats). Меня интересует встроенный тип событий: app_install.

Подскажите, пожалуйста, как можно с помощью пакета получить данные по количеству установок приложения?

Функция, которой я пользовался:
fbGetMarketingStat(accounts_id = "act_460299487329887",
                                                  level = "adset",
                                                  fields = "campaign_name,adset_name,clicks,impressions,reach,actions",
                                                  date_start = "2018-08-01",
                                                  date_stop = "2018-08-07",
                                                  interval = "day",
                                                  api_version = 'v3.1',
                                                  access_token = token)

Ошибку, которую я получаю: http://prntscr.com/kfnr34

Заранее спасибо!

**Comment by selesnow** [comment]
На днях попробую разобраться, скорее всего вам надо использовать аргумент action_breakdown, пока посмотрите справку - [](https://developers.facebook.com/docs/marketing-api/insights/breakdowns/#actionsbreakdown) .

В функции fbGetMarketingStat есть одноимённый аргумент action_breakdowns , в который вам скорее всего надо передать значение action_type, думаю всё получится, попробуйте и напишите получилось или нет.

**Comment by rledovskiy** [comment]
@selesnow, спасибо за ответ!

Попробовал добавить в функцию аргумент:
action_breakdowns = "action_type",

Итоговая функция получилась:
                                                  fbGetMarketingStat(accounts_id = "act_460299487329887",
                                                  level = "campaign",
                                                  fields = "campaign_name,actions",
                                                  action_breakdowns = "action_type",
                                                  date_start = "2018-08-01",
                                                  date_stop = "2018-08-07",
                                                  api_version = 'v3.1',
                                                  interval = "month",
                                                  access_token = token)

К сожалению, результат остался такой же: http://prntscr.com/kg1cgj

**Comment by selesnow** [comment]
Сегодня выяснил причину этой ошибки,  проблема в том, что когда вы запрашиваете поле actions или action_values, API Facebook отдаёт в качестве результата не таблицу, а сложную структуру, которую проблематично привести к табличной форме, так что бы не сломать всё остальное.

*Пометка для меня* ошибка в 200 строке функции [fbGetMarketingStats](https://github.com/selesnow/rfacebookstat/blob/master/R/fbGetMarketingStat.R).

**Comment by Pallich** [comment]
> Сегодня выяснил причину этой ошибки, проблема в том, что когда вы запрашиваете поле actions или action_values, API Facebook отдаёт в качестве результата не таблицу, а сложную структуру, которую проблематично привести к табличной форме, так что бы не сломать всё остальное.
> 
> _Пометка для меня_ ошибка в 200 строке функции [fbGetMarketingStats](https://github.com/selesnow/rfacebookstat/blob/master/R/fbGetMarketingStat.R).

Добрый день.
Алексей, так и не удалось решить проблему с получением значения поля actions?
Есть вообще какие то варианты получения этих данных?

Спасибо.

**Comment by selesnow** [comment]
Проблема в наличии времени на такую большую доработку, т.к данные по action_breakdowns сам facebook отдаёт в дичайшей структуре.

На данный момент у меня очень большой загруз на работе + поддержка студентов моего курса, поэтому я даже примерно не могу сказать когда до этого доберусь, но точно не раньше лета.

**Comment by Pallich** [comment]
> Проблема в наличии времени на такую большую доработку, т.к данные по action_breakdowns сам facebook отдаёт в дичайшей структуре.
> 
> На данный момент у меня очень большой загруз на работе + поддержка студентов моего курса, поэтому я даже примерно не могу сказать когда до этого доберусь, но точно не раньше лета.

Возможно вы можете подсказать какие то другие способы получения данной информации?
Может это не с помощью fbGetMarketingStats или даже не API Marketing?
Направьте плз хотя бы.

Спасибо.

**Comment by selesnow** [comment]
Добрый день, у меня для вас хорошие новости по этому тикету - https://github.com/selesnow/rfacebookstat/releases/tag/1.9.0

Если такое решение вас устраивает прошу закрыть тикет.

**Comment by selesnow** [comment]
Уже можно загрузить исправленную версию даже с CRAN.

`install.packages("rfacebookstat")`

В связи с отсутствием реакции постановщика тикет закрываю.
